# @name login 
POST http://localhost:8000/login
Content-Type: application/json

{
  "email":"nacho@gmail.com",
  "password":"prueba123"
}

###
GET http://localhost:8000/movies
Authorization: Bearer {{ login.response.body.token }}

###
GET http://localhost:8000/directors

###
POST http://localhost:8000/directors
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "name":"Christopher",
  "lastname":"Nolan"
}

###
POST http://localhost:8000/movies
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "title" : "Interstelar",
  "directorId": 1,
  "year": 2014,
  "rating": 8.2,
  "genres": "Ciencia ficción"
}

###


POST http://localhost:8000/directors
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "name":"Martin",
  "lastname":"Scorsese"
}

###
GET http://localhost:8000/directors/

###
DELETE  http://localhost:8000/directors/6
Authorization: Bearer {{ login.response.body.token }}