# @name login 
POST http://localhost:8000/login
Content-Type: application/json

{
  "email":"nacho@gmail.com",
  "password":"prueba123"
}

###
POST http://localhost:8000/directors
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "name":"Christopher",
  "lastname":"Nolan"
}

###

POST http://localhost:8000/directors
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "name":"Martin",
  "lastname":"Scorsese"
}

###

GET http://localhost:8000/directors
###

GET http://localhost:8000/users


###

POST http://localhost:8000/users/
Content-Type: application/json

{
  "name":"Ignacio",
  "lastname":"González",
  "email":"nacho@gmail.com",
  "password":"prueba123"
}

###

GET http://localhost:8000/users/11

###

DELETE  http://localhost:8000/users/19

###

PUT http://localhost:8000/users/12
Content-Type: application/json

{
  "name":"AIgnacio",
  "lastname":"González",
  "email":"nacho@gmail.com",
  "password":"prueba"
}